# Generated by Django 2.1.1 on 2018-09-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField()),
                ('SellPrice', models.IntegerField(null=True)),
                ('Cost', models.IntegerField()),
                ('Author', models.CharField(max_length=200)),
                ('Status', models.CharField(choices=[('Dispatch', 'Item is on a way'), ('Sold', 'Item is out of Stock'), ('Available', 'Item is in Stock')], default='', max_length=10)),
                ('Type', models.CharField(choices=[('Non-Fiction', 'Non-Fiction'), ('Fiction', 'Fiction')], default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField()),
                ('SellPrice', models.IntegerField(null=True)),
                ('Cost', models.IntegerField()),
                ('Color', models.CharField(default='', max_length=200)),
                ('Brand', models.CharField(default='', max_length=200)),
                ('Status', models.CharField(choices=[('Dispatch', 'Item is on a way'), ('Sold', 'Item is out of Stock'), ('Available', 'Item is in Stock')], default='', max_length=10)),
                ('Type', models.CharField(choices=[('Old', 'Old'), ('New', 'New'), ('Refurbished', 'Refurbished')], default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField()),
                ('SellPrice', models.IntegerField(null=True)),
                ('Cost', models.IntegerField()),
                ('Color', models.CharField(default='', max_length=200)),
                ('Brand', models.CharField(default='', max_length=200)),
                ('Status', models.CharField(choices=[('Dispatch', 'Item is on a way'), ('Sold', 'Item is out of Stock'), ('Available', 'Item is in Stock')], default='', max_length=10)),
                ('Type', models.CharField(choices=[('Old', 'Old'), ('New', 'New'), ('Refurbished', 'Refurbished')], default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Quantity', models.IntegerField()),
                ('SellPrice', models.IntegerField(null=True)),
                ('Cost', models.IntegerField()),
                ('Brand', models.CharField(default='', max_length=200)),
                ('Status', models.CharField(choices=[('Dispatch', 'Item is on a way'), ('Sold', 'Item is out of Stock'), ('Available', 'Item is in Stock')], default='', max_length=10)),
                ('Type', models.CharField(choices=[('Old', 'Old'), ('New', 'New'), ('Refurbished', 'Refurbished')], default='', max_length=100)),
            ],
        ),
    ]
