# Generated by Django 2.1.1 on 2018-09-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Status',
            field=models.CharField(choices=[('Available', 'Item is in Stock'), ('Dispatch', 'Item is on a way'), ('Sold', 'Item is out of Stock')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Status',
            field=models.CharField(choices=[('Available', 'Item is in Stock'), ('Dispatch', 'Item is on a way'), ('Sold', 'Item is out of Stock')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Type',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('Refurbished', 'Refurbished')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='Status',
            field=models.CharField(choices=[('Available', 'Item is in Stock'), ('Dispatch', 'Item is on a way'), ('Sold', 'Item is out of Stock')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='Type',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('Refurbished', 'Refurbished')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='other',
            name='Status',
            field=models.CharField(choices=[('Available', 'Item is in Stock'), ('Dispatch', 'Item is on a way'), ('Sold', 'Item is out of Stock')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='other',
            name='Type',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('Refurbished', 'Refurbished')], default='', max_length=100),
        ),
    ]
