# Generated by Django 2.1.1 on 2018-09-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20180930_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Type',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction')], default='', max_length=100),
        ),
    ]
